CXX = g++
CXXFLAGS = -std=c++17 -Wall -Iinclude


SRC = src/Process.cpp
TEST = tests/test_process.cpp
OBJ = $(SRC:.cpp=.o)
TARGET = test_process

all: $(TARGET)

$(TARGET): $(OBJ) $(TEST)
	$(CXX) $(CXXFLAGS) $(OBJ) $(TEST) -o $(TARGET)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f src/*.o $(TARGET)

run: $(TARGET)
	./$(TARGET)
