CXX = g++
CXXFLAGS = -std=c++17 -Wall -g

SRCS = src/Process.cpp src/Pipe.cpp tests/test_process.cpp
OBJS = $(SRCS:.cpp=.o)
TARGET = test_process

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(OBJS) -o $(TARGET)

# Для файлів у src/
src/%.o: src/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Для файлів у корені (як test_process.cpp)
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f src/*.o *.o $(TARGET)
	rm -f tests/*.o *.o $(TARGET)
